spring:
  profiles:
    active: 
    - dev
---
spring:
  profiles: dev
  application:
    name: test1
server:
  port: 80
--- 
spring:
  profiles: beta
  application:
    name: msg
---
spring:
  profiles: new
  application:
    name: newMsg:wq
